nodeLinker: pnp

packageExtensions:
  "vite@*":
    peerDependencies:
      esbuild: "*"
  "@vitejs/plugin-react@*":
    peerDependencies:
      esbuild: "*"
  
  "@exodus/bytes@*":
    dependencies:
      "base-x": "*" 
