approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

packageExtensions:
  "@exodus/bytes@*":
    dependencies:
      base-x: "*"
  "@vitejs/plugin-react@*":
    peerDependencies:
      esbuild: "*"
  vite@*:
    peerDependencies:
      esbuild: "*"
